image: microsoft/dotnet:latest

before_script:
  - apt-get update
  - apt-get install -y make

stages:
  - build
  - test

build:
  stage: build
  script:
    - make build
  artifacts:
    untracked: true

test:
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - make unit-tests
  artifacts:
    paths:
    - artefacts/testResults/UnitTests.trx