stages:
  - build
  - unit-tests

build:
  image: joshkeegan/dotnet-build:2.2.100.0
  stage: build
  script:
    - make publish-all
  artifacts:
    paths:
      - artefacts
      - StringSearch.Api/out
      - UnitTests/Makefile
      - UnitTests/UnitTests.csproj
      - UnitTests/out
    expire_in: 30 minutes

unit-tests:
  image: joshkeegan/dotnet-build:2.2.100.0
  stage: unit-tests
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none
  script:
    - cd UnitTests
    - make run
  artifacts:
    paths:
      - artefacts/testResults/UnitTests.trx