stages:
  - build
  - unit-tests
  - generate-docker-images
  - deploy-prod

build:
  tags:
    - big-cpu
  image: joshkeegan/dotnet-build:2.2.100.0
  stage: build
  script:
    - make publish-all
  artifacts:
    paths:
      - artefacts
      - sharedScripts
      - StringSearch.Api/Dockerfile
      - StringSearch.Api/out
      - UnitTests/Makefile
      - UnitTests/UnitTests.csproj
      - UnitTests/out
      - Makefile
    expire_in: 30 minutes

unit-tests:
  tags:
    - big-mem
  image: joshkeegan/dotnet-build:2.2.100.0
  stage: unit-tests
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none
  script:
    - cd UnitTests
    - make run
  artifacts:
    paths:
      - artefacts/testResults/UnitTests.trx

generate-docker-images:
  tags:
    - docker
  image: docker:stable
  services:
    - docker:dind
  only:
    refs:
      - master
      # TODO: Remove once finished developing this
      - gitlabDocker
  stage: generate-docker-images
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none
  script:
    - apk add --no-cache make
    - make crUsername="$CR_USERNAME" crPassword="$CR_PASSWORD" buildId="$CI_JOB_ID" commitHash="${CI_COMMIT_SHA:0:8}" publish-api-image
  artifacts:
    paths:
      - artefacts/deploy
      - artefacts/uniqueifier
      - sharedScripts

#TODO: Use environments & don't go straight to prod (https://docs.gitlab.com/ee/ci/environments.html)

deploy-prod:
  image: kroniak/ssh-client:3.6
  only:
    refs:
      - master
      # TODO: Remove once finished developing this
      - gitlabDocker
  stage: deploy-prod
  dependencies:
    - generate-docker-images
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY_PROD" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - uniqueifier=`cat artefacts/uniqueifier`
    - ssh $DEPLOY_USERNAME_PROD@$DEPLOY_HOSTNAME_PROD "mkdir -p ~/PiSearch/cd/prod/$uniqueifier"
    - scp -r . $DEPLOY_USERNAME_PROD@$DEPLOY_HOSTNAME_PROD:~/PiSearch/cd/prod/$uniqueifier
    - ssh $DEPLOY_USERNAME_PROD@$DEPLOY_HOSTNAME_PROD "cd ~/PiSearch/cd/prod/$uniqueifier/artefacts/deploy; make rootPath=\"/var/www/pi_digits\" environment=\"Production\" appsettingsDir=\"/var/www/v2.api.pisearch.joshkeegan.co.uk\" deploy"