image: microsoft/dotnet:latest

before_script:
  - apt-get update
  - apt-get install -y make
  - dotnet restore

stages:
  - test

test:
  stage: test
  script:
    - make build
    - make unit-tests
  artifacts:
    paths:
    - artefacts/testResults/UnitTests.trx