image: microsoft/dotnet:latest

before_script:
  - apt-get install -y make
  - dotnet restore

stages:
  - test

test:
  stage: test
  script:
    - make build
    - make unit-tests-linux
  artifacts:
    paths:
    - UnitTests/TestResults/UnitTests.trx