image: microsoft/dotnet:latest

before_script:
  - dotnet restore

stages:
  - test

test:
  stage: test
  script:
    - dotnet build
    - cd UnitTests
    - dotnet test --filter TestCategory!=windows