version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "live"

  - package_manager: "docker"
  directory: "/src/StringSearch.Api.Host"
  update_schedule: "daily"